#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use SensioLabs\Security\Command\SecurityCheckerCommand;
use SensioLabs\Security\SecurityChecker;

$console = new Application('SensioLabs Security Checker', '1.0');
$console->add(new SecurityCheckerCommand(new SecurityChecker()));
$console->run();
